// <auto-generated />
namespace MemberShipsPro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CancelUpdateUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CancelUpdateUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "202004020514333_CancelUpdateUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
